import Head from "next/head";
import Header from "../components/Header";
import Landing from "../components/Landing";

export default function Home() {
  return (
    <div className=''>
      <Head>
        <title>Apple Redesign</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header />

      <main className='relative h-[200vh]'>
        <Landing />
      </main>
    </div>
  );
}
